# Generated by Django 5.0.6 on 2024-07-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
