# Generated by Django 5.0.6 on 2024-07-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productmodel_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_img',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
